name: Release Helm Chart

on:
  push:
    branches:
      - master
      - release-1.0
    paths:
      - "helm/ovn-kubernetes/**"  # Watch for changes in the Helm charts directory

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3  # Use the latest Helm version

      # Step 3: Install chart-releaser
      - name: Install chart-releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.5.0/chart-releaser_1.5.0_linux_amd64.tar.gz | tar xz
          sudo mv cr /usr/local/bin/

      # Step 4: Extract repository owner
      - name: Extract repository owner
        id: repo_info
        run: echo "owner=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f1)" >> $GITHUB_ENV

      # Step 5: Run chart-releaser to package and upload charts
      - name: Package and Upload Helm Charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd helm/ovn-kubernetes
          cr package charts/
          cr upload -o ${{ env.owner }} -r $(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)

      # Step 6: Update GitHub Pages index
      - name: Update GitHub Pages Index
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd helm/ovn-kubernetes
          cr index -o ${{ env.owner }} -r $(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)

